# Generated by Django 4.0.6 on 2022-07-10 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('dogs', models.ManyToManyField(blank=True, related_name='dogs', to='base.dog')),
                ('referee1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee1', to=settings.AUTH_USER_MODEL)),
                ('referee2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee2', to=settings.AUTH_USER_MODEL)),
                ('referee3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('legs', models.IntegerField(default=0)),
                ('tail', models.IntegerField(default=0)),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.dog')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.show')),
            ],
        ),
    ]
