# Generated by Django 4.0.6 on 2022-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_show_address_show_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='show',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
