# Generated by Django 4.0.6 on 2022-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_show_options_show_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(default='Punktacja', max_length=200),
            preserve_default=False,
        ),
    ]
