# Generated by Django 4.0.6 on 2022-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_score_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
