# Generated by Django 4.0.6 on 2022-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_score_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(default='color', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
