# Generated by Django 4.0.6 on 2022-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_dog_color_dog_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_img',
            field=models.ImageField(default='img/dog_default.jpg', upload_to='img/'),
        ),
    ]
