# Generated by Django 4.0.6 on 2022-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, default='img/default_avatar.jpg', upload_to='static/img'),
        ),
    ]
