# Generated by Django 4.0.6 on 2022-10-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_show_options_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.TextField(default='Guest', max_length=50),
        ),
    ]
